### ISSUE TITLE
chopped/incorrect rendering in overview mode

### ISSUE THREAD

**Issue by natask** [maiself/gnome-shell-extension-invert-color#10]
The issue is that windows get render chopped and sometimes don't render at all the left area of  overview mode. windows also sometimes don't render in the right area of the overview mode where different virtual workspaces are rendered. over all there is incompatibility between this extension and the overview mode.
I was able to isolate the issue to the call ```actor.add_effect_with_name('invert-color', effect);``` and even tried calling it with an effect object that doesn't do anything but still faced the same issue. I experimented a bit and found that the size of the window determines whether it is going to be chopped or not and that the window doesn't render in the small overview box to the right if the virtual workspace is focused and it is the only window in that virtual workspace. my assumption is that there is an incompatibility the add_effect method that the extension uses and how overview renders these windows. 

are there any alternatives to the overview mode for gnome? any solutions to this issue? I will look into gnome-shells implementation for the overview mode for inspirations.

I am using ubuntu 18.04 latest version, gnome shell 3.28.3.

**Comment by natask** [comment]
![image](https://user-images.githubusercontent.com/39103342/55218309-16ded980-51d8-11e9-8105-bf45d1f4ae9b.png)
![image](https://user-images.githubusercontent.com/39103342/55219115-69b99080-51da-11e9-91d4-03979d972b7c.png)
![image](https://user-images.githubusercontent.com/39103342/55219151-82c24180-51da-11e9-911a-8d79d798d9d7.png)
![image](https://user-images.githubusercontent.com/39103342/55219181-940b4e00-51da-11e9-8383-8866054bfd4b.png)
![image](https://user-images.githubusercontent.com/39103342/55219193-9cfc1f80-51da-11e9-94a9-d1659b466ed5.png)
![image](https://user-images.githubusercontent.com/39103342/55219210-ac7b6880-51da-11e9-8958-5a208bde2769.png)
![image](https://user-images.githubusercontent.com/39103342/55219215-b3a27680-51da-11e9-8a9d-2265275cc617.png)

**Comment by maiself** [comment]
This was a long existing bug in the window manager that's recently been [fixed](https://gitlab.gnome.org/GNOME/mutter/commit/8655bc5d8de6a969e0ca83eff8e450f62d28fbee). The fix made it into 3.32, unfortunately old versions will still have the bug and this cant be fixed from the extension.

**Comment by natask** [comment]
thanks, good thing this is fixed. currently I am calling xrandr-invert-colors from the extension when overview is shown or hidden and turning off/on inversion respectively to avoid this. gnome-shell 3.32 is hot of the stove so I am hesitant to use it on my main machine but I will try it out on a spare distro.  @maiself Have you personally verified that this is not a issue on gnome shell 3.32 and on what distro? I see that the manifest file declares gnome 3.32 as supported.

**Comment by maiself** [comment]
I'm using Arch Linux which currently has version 3.32. I wouldn't have updated the manifest if it didn't work as intended.

**Comment by natask** [comment]
@maiself the fix for the bug you reported and fixed propagated down to the latest version of gnome-shell Ubuntu (either 3.28 or 3.30 I will check later) 18.04 uses. Been using it for around ever since June.
