### ISSUE TITLE
Broken under 3.36

### ISSUE THREAD

**Issue by p3732** [maiself/gnome-shell-extension-invert-color#13]
Loving this extension, really useful whenever something is way too bright at night. Unfortunately it stopped working with 3.36. All it does is make the window invisible. It otherwise works correctly, the window can be made visible by pressing the shortcuts again. The extension does not log any errors either.

Side note: I tried the fix proposed in #1 and it does not help either, so it probably is some broken API that changed in the shell...

**Comment by maiself** [comment]
Thanks for pointing this out, I've fixed it with 0e70aae1671. Glad you are enjoying the extension :D

**Comment by p3732** [comment]
Thank  you very much! Working smoothly again now :tada:
