### ISSUE TITLE
InvertColors is reverted on lock and unlock screen

### ISSUE THREAD

**Issue by fastrizwaan** [maiself/gnome-shell-extension-invert-color#2]
After locking the screen (super+L) and unlocking, the inverted window becomes normal.

How to reproduce:
1. invert a window using super+i
2. lock screen (press super+L)
3. unlock the screen
4. we can see that the window becomes un-inverted on unlock.

please let unlock keep the invert on.

**Comment by maiself** [comment]
This had been bugging me for a while, finally fixed! :D

4ca4bb3f6e83f17a1ae7746b245fd4df0dbe310d
