### ISSUE TITLE
inverted window shadow in gnome 3.18.4 (fedora 23) shadow turns thick black

### ISSUE THREAD

**Issue by fastrizwaan** [maiself/gnome-shell-extension-invert-color#3]
Please see the inverted window, there is a black border around the  window. Thanks
![screenshot from 2016-04-02 07-11-14](https://cloud.githubusercontent.com/assets/1161682/14223725/541fc904-f8a2-11e5-933e-89ede62af721.png)

**Comment by maiself** [comment]
This could be a difference in handling of division by zero errors by the driver. Could you please test this branch and report back if it fixes the issue or not?

535d547b80596cce33339753c24d3d7d53f11e01

**Comment by fastrizwaan** [comment]
sure, by tomorrow.

**Comment by fastrizwaan** [comment]
working, thanks.

![screenshot from 2016-04-03 14-42-44](https://cloud.githubusercontent.com/assets/1161682/14231702/6f117164-f9aa-11e5-82e9-ccb1388b51ff.png)

**Comment by maiself** [comment]
Awesome, thanks for testing!

Fixed in 535d547b80596cce33339753c24d3d7d53f11e01
