### ISSUE TITLE
Cannot Configure Key Binding

### ISSUE THREAD

**Issue by limitedAtonement** [maiself/gnome-shell-extension-invert-color#7]
This application is working well, but I would rather `<Super>n`. `<Super>i` is terribly inconvenient on the dvorak keyboard when the `<Super>` key is under the left hand. I don't see any way to configure it using gnome tweak tool nor gnome standard settings. I'm new to gnome, though, so perhaps I'm missing it.

**Comment by maiself** [comment]
You used to be able to do this with `dconf-editor` but that seems to have changed. Depending on your distro that may still be an option. A for sure way to change the key binding to `<Super>N` is this command:

`gsettings --schemadir ~/.local/share/gnome-shell/extensions/invert-window@maiself/schemas/ set org.gnome.shell.extensions.invert-window invert-window-shortcut '["<Super>N"]'`

I've been wanting to add a UI for configuring this and other options, but unfortunately haven't had time to do so.

**Comment by limitedAtonement** [comment]
Thank you so much! I think a UI for this would be a waste of time for you and users. Configuration files (or gconf) is 1) easy for you to develop, 2) common for many programs, so easy for users to understand, and 3) easy for users to script (so I can migrate my settings from here to there.

The extension is working beautifully! XFCE doesn't have anything like this, so I was getting by with just xcalib -i -a; Now I am still using xcalib -i -a to get the whole screen light-on-dark, but now I can switch just one window (for watching a video, looking at pictures, etc.). Rock on!
